### ISSUE TITLE
Should return 403 Forbidden when permission denied

### ISSUE THREAD

**Issue by pkkid** [flavors/django-graphql-extensions#1]
This project is properly blocking access. However when using libraries that check status codes, a 200 looks like a success, when it really isn't.

**Comment by pkkid** [comment]
I was able to work around this using Axios as my front end client by adding the following code to check for the 'errors' key in a success response. However, this library should still return a proper 403 when responding with permission denied.

```javascript
import axios from 'axios';

// Tell Axios we want to treat any non-json responses as errors
// as well as any responses containing the key 'errors'
axios.interceptors.response.use(function(response) {
  if (response.headers['content-type'] != 'application/json') { return Promise.reject(response); }
  else if (response.data.errors !== undefined) { return Promise.reject(response); }
  else { return response; }
});
```

**Comment by mongkok** [comment]
It's common/good practice to use HTTP 200 for all GraphQL responses, GraphQL doesn't care about the transport layer.
On the other hand consider that GraphQL supports multiple operations in a single request, some operations may have an authentication error and others may not.

I close the issue, if you have any questions please let me know.
